### PR TITLE
Added new parameter read_timeout and baudrate_read

### PR DESCRIPTION
**Pull request by hvorragend**
It would be very nice if you can check and accept this soon. Thank you very much.

### CODE REVIEW

**Comment by m-reuter** [comment]
Sure, and thanks.

**Comment by hvorragend** [comment]
I don't know why, but there is something wrong now.

I cannot start the addon:

`s6-overlay-suexec: fatal: can only run as pid 1`

**Comment by hvorragend** [comment]
Perhaps it is related with https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

**config.yaml**
`init: false`

**Comment by m-reuter** [comment]
Thanks, yes that is probably it. I updated the config file in the meantime, let me know if it works. Thanks.

**Comment by hvorragend** [comment]
Works fine now. 
thank you.

**Pull request merged**
